# Torch tensors

In [1]:
# Torch tensors introduction

## Introduction: creating tensors

import torch

# Creating a tensor
x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [2]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [3]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
import torch

# Create a tensor with requires_grad=True to track computations
a = torch.tensor(5.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

# Define a simple function y = x^3 + 3x^2 + 5
y = 3*a*b**2 + a**2 + b 

# Compute gradients
y.backward()

# Gradient is stored in a.grad and b.grad
print(a.grad)
print(b.grad)


tensor(37.)
tensor(91.)


# Quesion : Can you write a gradient descent algorithm to train a single perceptron with pytorch? you can chose whatever binary classification problem you want.